dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]

rubocop:
  script:
    - rubocop

test-ruby-2.3.7:
  image: ruby:2.3.7
  script:
    - bundle install --binstubs
    - bundle exec rake test
    - bundle exec rake spec

test-ruby-2.4.4:
  image: ruby:2.4.4
  script:
    - bundle install --binstubs
    - bundle exec rake test
    - bundle exec rake spec

test-ruby-2.5.1:
  image: ruby:2.5.1
  script:
    - bundle install --binstubs
    - bundle exec rake test
    - bundle exec rake spec