language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.0
notifications:
  email: false
before_install:
  - gem update --system
  - gem update bundler
script: bundle exec rake $TASK
env:
- TASK=test
- TASK=spec
